#ifndef _DEFINES_SDL_H_
#define _DEFINES_SDL_H_

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 700

#define SCREEN_WIDTH_HALF SCREEN_WIDTH/2
#define SCREEN_HEIGHT_HALF SCREEN_HEIGHT/2

#define NUMBER_PARTICLES 4

#endif //_DEFINES_SDL_H_